name: Test Linux Setups

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: ["ubuntu16.04", "centos7"]

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ matrix.container }} .
        working-directory: ${{ matrix.container }}
      - name: Run Docker image and install hello
        run: docker run --rm ${{ matrix.container }} "brew install hello && brew test hello"
