name: Test Linux Setups

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container: [
          "ubuntu16.04",
          "ubuntu18.04",
          "ubuntu20.04",
          "ubuntu22.04",
          "centos7",
          "centos8",
          "debian7",
          "debian8",
          "debian9",
          "debian10",
          "debian11",]

    steps:
      - uses: actions/checkout@v2
      - name: Build Docker image
        run: docker build -t ${{ matrix.container }} .
        working-directory: nightly-linux/${{ matrix.container }}
      - name: Run tests
        run: docker run --rm --user linuxbrew -w /home/linuxbrew -v $(pwd)/nightly-linux/test.sh:/home/linuxbrew/test.sh ${{ matrix.container }} /bin/bash -i -c ./test.sh
