name: Test Linux Setups

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [
          "ubuntu:16.04",
          "ubuntu:18.04",
          "ubuntu:20.04",
          "debian/eol:wheezy",
          "debian/eol:jessie",
          "debian/eol:stretch",
          "debian:buster",
          "debian:bullseye"]

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Install Pre-requisites
        run: apt-get update && apt-get install -y build-essential curl git

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Add brew to path          
        run: |
          test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
          test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.bash_profile
          echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.profile
          source ~/.profile

      - name: Update Homebrew
        run: brew update

      - name: Install hello
        run: brew install hello

      - name: Test hello
        run: brew test hello
