name: Test Linux Setups

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container: [
          "ubuntu:16.04",
          "ubuntu:18.04",
          "ubuntu:20.04",
          "debian/eol:wheezy"]

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Install Pre-requisites
        run: apt-get update && apt-get install -y build-essential curl git

      - name: Install tar if necessary
        if: matrix.container == 'debian/eol:wheezy'
        run: |
          curl -sL http://ftp.gnu.org/gnu/tar/tar-1.32.tar.gz | tar xz
          cd tar-1.32
          FORCE_UNSAFE_CONFIGURE=1 ./configure --prefix=/usr/local
          make install
          cd .. && rm -rf tar-1.32
          ln -fs /usr/local/bin/tar /usr/bin/tar

      - name: Install git if necessary
        if: matrix.container == 'debian/eol:wheezy'
        run: |
          apt-get install -y autoconf zlib1g-dev gettext
          curl -sL http://mirrors.edge.kernel.org/pub/software/scm/git/git-2.28.0.tar.gz | tar xz
          cd git-2.28.0
          make configure
          ./configure --prefix=/usr/local
          make install NO_TCLTK=1
          cd .. && rm -rf git-2.28.0
          ln -fs /usr/local/bin/git /usr/bin/git

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Add brew to path          
        run: |
          test -d ~/.linuxbrew && eval "$(~/.linuxbrew/bin/brew shellenv)"
          test -d /home/linuxbrew/.linuxbrew && eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          test -r ~/.bash_profile && echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.bash_profile
          echo "eval \"\$($(brew --prefix)/bin/brew shellenv)\"" >>~/.profile
          . ~/.profile

      - name: Update Homebrew
        run: brew update

      - name: Install hello
        run: brew install hello

      - name: Test hello
        run: brew test hello
